changes to support heater and spa mode
had to make changes to noImplicitAny due to the following error during build.  

error TS7016: Could not find a declaration file for module '@homebridge/dbus-native'